name: Deploy Flask Static Site

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r dependencies.txt

      # Build the static site with Flask-Freeze
      - name: Build site
        env:
          FLASK_APP: app.py
        run: flask freeze

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Match Flask-Freeze's output directory

 